web/src/components/graph/FactoryNode.vue, web/src/components/planner/PlannerFactory.vue, web/src/components/planner/PlannerFactoryExportCalculator.vue, web/src/components/planner/PlannerFactoryExports.vue, web/src/components/planner/PlannerFactoryImports.vue, web/src/components/planner/PlannerFactoryProducts.vue, web/src/components/planner/PlannerFactorySatisfaction.vue, web/src/utils/numberFormatter.ts
This is an effort to format all of the numbers with the same formatting rules. Strip off zeros to 2 decimal places max.
Hopefully it's not controversial - I'm not great with vue, and had to hack a little to get there - I think the result is solid, but no hard feelings if this is not accepted. This partly addresses #10. 
- If the number is 2.0 or 2.00, show `2`
- If the number is 2.5 or 2.50, show `2.5`
- If the number is 2.25 or 2.250, show `2.25`
- If the number is 2.333, show `2.33`
<HR>
**Copilot generated description:**
This pull request focuses on improving the consistency and readability of numerical values displayed in various Vue components by introducing a new utility function, `formatNumber`, and applying it across multiple files. The most important changes include the addition …
=> Format numbers with extra decimal places to the max of 2 decimal places, and reduce numbers that don't need the accuracy.

package-lock.json, parsing/src/interfaces/Recipe.ts, parsing/src/processor.ts
Fixes #59 
<HR>
Update `parsing/src/interfaces/Recipe.ts` and `parsing/src/processor.ts` to ensure `power` is a number.
* Change `power` type from `string` to `number` in the `Recipe` interface in `parsing/src/interfaces/Recipe.ts`.
* Change `power` type from `string` to `number` in the `building` object of the `Recipe` interface in `parsing/src/processor.ts`.
* Parse `power` as a number in the `getRecipes` function in `parsing/src/processor.ts`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/Maelstromeous/satisfactory-factories/pull/68?shareId=dd68e51f-cb9d-4a85-8b91-f0811672bf60).
=> Ensure power is a number throughout all code

.github/workflows/issue-management.yml
This pull request includes a change to the `.github/workflows/issue-management.yml` file to improve the issue management workflow by removing the 'Needs Triage' label from issues.
=> feat(workflow): Remove 'Needs Triage' label from issues after adding P1 label

.github/workflows/builds.yml
This pull request includes a small change to the `.github/workflows/builds.yml` file. The change adds a new step to test the parsing after the build step in the workflow.
=> fix: Enabling parsing tests

web/src/utils/factory-management/buildings.ts, web/src/utils/factory-setups/simple-plan.spec.ts
fixes #154
Keeping this PR a bit smaller. This corrects power to match other calculators for basic machines, fixing the under-clocking issues that existed (e.g. not Quantum encoders/ particle accelerators, etc)
=> Power updates to use correct underclocking formula

parsing/gameData.json, parsing/src/recipes.ts, web/public/gameData_v1.0-21.json, web/src/config/config.ts
fixes #158
Incorrectly transferred the recipes for [Uranium Waste](https://satisfactory.wiki.gg/wiki/Uranium_Fuel_Rod) and [Plutonium Waste](https://satisfactory.wiki.gg/wiki/Plutonium_Fuel_Rod). This fixes that. 
<HR>
This pull request includes several changes to the `parsing` and `web` directories to update the processing and display of nuclear and plutonium waste production rates. The most important changes include modifying the production rates in the data files and updating the configuration to reflect the new data version.
=> Fix to nuclear waste

web/src/components/planner/Notice.vue
This pull request includes updates to the `Notice.vue` component in the `planner` directory. The primary changes involve reclassifying several issues from 'open' to 'closed' and removing them from the 'open' issues list.
=> Updated bug list after weekend power spike

web/src/components/planner/PlannerFactoryProducts.vue
fixes #171 
Previously logic was only looking if there were ingredients before showing/hiding the row, but some parts (in phase 5), do not have ingredients - just power and a product.
<HR>
This pull request includes an important change to the `PlannerFactoryProducts.vue` file to improve the display logic for product requirements.
=> Fixes bug to show details for part with no ingredients

parsing/gameData.json, parsing/src/recipes.ts, parsing/tests/parsing.spec.ts, web/public/gameData_v1.0-22.json, web/src/config/config.ts
The recipe for Neural-Quantum Processor has a minimum power of 0 and a max power of 2000. The Average should be 1000, but it wasn't. Because of this conditional. 
```
if (lowPower && highPower) {
powerPerBuilding = (lowPower + highPower) / 2;
}
```
Now this is checking to make sure the low and high value is truthy - e.g. not false, 0, "", null, undefined or NaN. See the problem there? I didn't initially... but because the low value is 0 - it was basically considered null, and didn't calculate the average for this recipe. Here is the new code:
```
if (lowPower != null && highPower != null) {
powerPerBuilding = (lowPower + highPower) / 2;
}
```
=> Fixes quantum power calculation

web/src/components/planner/PlannerFactory.vue
- Added a section on hidden factories to show 'Import' (modeled just like Exports)
No Imports
Factory Satisfied Imports
Factory Not Satisfied Imports
Closes #6
=> Added Imports to show while Factory is hidden

web/src/components/planner/PlannerFactoryImports.vue, web/src/components/planner/PlannerFactoryProducts.vue
=> Fix quantity inputs

web/src/components/planner/PlannerFactoryImports.vue
Moving this message back outside the loop, as it is supposed to go here
Should be fixed now
Closes #211
=> fix(web): Fixing Raw Resource Import message

web/src/components/ShareButton.vue, web/src/components/planner/PlannerFactory.vue, web/src/stores/auth-store.ts
iOS has a very annoying issue where all browsers upon it do not allow the `navigator.clipboard` API without a user interaction attached.
In the event the user agent doesn't support clipboard API, the user is shown a simple dialog with a button to copy the link directly.
=> Fix sharing process for iOS users

web/index.html, web/src/App.vue, web/src/assets/styles/global.scss, web/src/components/planner/PlannerFactory.vue, web/src/components/planner/PlannerFactoryList.vue, web/src/interfaces/planner/FactoryInterface.ts, web/src/stores/app-store.ts, web/src/utils/factory-management/factory.ts, web/src/utils/factory-management/syncState.spec.ts, web/src/utils/factory-management/syncState.ts
Closes #222 
This PR enables the user to do the following:
- Mark a factory as "in sync with game" denoting that they have done what the plan says in game
- Mark a factory as "out of sync" as a todo for them to fix later
- When a factory is marked as In Sync, the values of the products are saved. When the products get updated, the factory falls out of sync which the user then needs to put it back in sync.
- This feature is optional, the factory is created as `inSync: null` and when they mark it as sync for the first time does it then start tracking the sync state.
- I've updated the Factory List to be 1) more compact and 2) integrate the sync status.
Video https://youtu.be/dA4O4CMNi1Q
=> feat(web): Added ability to mark factories as out of sync with the game so the user can check them

web/src/utils/factory-management/dependencies.spec.ts, web/src/utils/factory-management/dependencies.ts, web/src/utils/factory-management/factory.ts
Fixes #228 
This adds a new step to calculateFactory to scan for potentially invalid imports and dependencies. This should stop the "invisible problem" bug where if someone managed to have old imports and they weren't removed properly.
=> fix(web): Prevent invalid imports and dependencies by scanning for them.

web/src/components/planner/PlannerFactoryImports.vue
Closes: #233 
Related: #58 
Redesigns imports section to use more vertical space. Removed Satisfied! button due to lack of usefulness
=> feat(repo): Optimised spacing on Imports section

web/src/components.d.ts, web/src/components/planner/Planner.vue, web/src/components/planner/PlannerFactory.vue, web/src/components/planner/PlannerFactoryList.vue, web/src/components/planner/PlannerFactoryNotes.vue, web/src/components/planner/PlannerFactoryTasks.vue, web/src/components/planner/PlannerFactoryTodos.vue, web/src/utils/factory-management/factory.spec.ts, web/src/utils/factory-management/factory.ts
Completes #261 
- The tasks chip is visible if there is at least one **incomplete** task, the number of which is displayed
- The notes chip is visible if there is any contents in the notes for the factory
- Clicking either chip will expand the factory and smooth scroll to the tasks / notes
**Note:** it now says "tasks" instead of "todos" but I don't want to re-create the screenshots haha
- New indicators for # of tasks or presence of notes
- Visibility conditions are the same as for the chips
- Clicking will scroll to the relevant section, just as with the chips
- Tooltip text matches the chip text (i.e. "Tasks: #" or "See notes")
- Icons are grey by default, white on hover to indicate they can be clicked
- Also fixed the wrapping on factory names, everything remains centered
=> Add notes and tasks indicators to the factory list and headers #261

parsing/gameData.json, parsing/package.json, parsing/src/parts.ts, parsing/tests/parsing.spec.ts, web/public/gameData_v1.0-26.json, web/src/config/config.ts
The first in a series of parser upgrades. 
This pull request includes updates to the raw resources data and related functionality in the parsing module to include missing raw resources and sort the final list of raw resources, ensuring the data file has the accurate list of raw resources. 
None of these new resources should appear in the statistics panel. There are a few recipes today that are missing these items, and will allow recipes using them to work. It's expected that the impact of this fix is very low, but we know some people creating [Ficmas recipes have noticed](https://github.com/satisfactory-factories/application/issues/274). 
fixes #274
=> fix: adding missing raw resources

web/src/components/planner/products/PowerProducer.vue
This change should fix #289
Looks like [toArray is only available in Firefox starting with 131](https://caniuse.com/?search=toArray), and the user reported running [floorp browser which is based on Firefox ESR (128)](https://www.reddit.com/r/Floorp/comments/1hdvmxr/useragent_for_floorp_identify_as_firefox_128/)
=> PowerProducer: fix browser compatibility for Firefox ESR

web/src/components/planner/products/Product.spec.ts, web/src/components/planner/products/Product.vue, web/src/setup-vitest.ts, web/src/stores/game-data-store.ts, web/src/stores/local-game-data-loader.ts, web/vite.config.mts
Fixes #173
This PR contains a bit of trickery I needed to make component tests work, otherwise they raised errors because:
- game data loading was browser-specific, the easiest way was to refactor it into a module and mock the loader to load from local file during tests instead
- pinia storage was not ready at the moment `@/utils/helpers` was imported, which executed `useGameDataStore()` at the top level, so i added a very early test setup to prepare pinia
I also added names for some of the inputs to simplify selecting them in tests. I don't have a strong opinions on what should be the final names for those.
=> Allow editing product ingredient amounts

web/src/components/planner/PlannerFactorySatisfactionItems.vue
Adds a little suffix to the parts 'remaining'. If it is a negative number (and is highlighted red), it shows the suffix 'shortage'.
=> fix: adding remaining label

web/src/components/Templates.vue, web/src/utils/factory-management/inputs.spec.ts, web/src/utils/factory-management/inputs.ts, web/src/utils/factory-setups/315-non-exportable-parts-imports.spec.ts, web/src/utils/factory-setups/315-non-exportable-parts-imports.ts
Closes #315 
Now correctly stops the user from selecting the part and also removes invalid imports for non exportable parts via `calculateFactories`.
=> 315 non exportable parts imports fix

web/src/components/Templates.vue, web/src/components/planner/PlannerFactoryImports.vue, web/src/utils/factory-management/dependencies.ts, web/src/utils/factory-management/inputs.spec.ts, web/src/utils/factory-management/inputs.ts, web/src/utils/factory-setups/251-redundant-import.ts, web/src/utils/factory-setups/324-redundant-import.ts
Closes #324 
Related: #299 
Inputs buttons now handle the following cases:
- If there are >1 inputs of the same part:
- If one input is satisfactory to fulfil demand, the other input(s) are marked as redundant to prompt the user to delete them. Largest is preferred, smallest ones will be flagged for deletion.
- If there is a deficit, pressing SATISIFY on an input will adjust the input to comply with the demand, taking into account other inputs of the same part and calculating the difference.
- This differs from the original issue where it was updating the value of the input to match the TOTAL requirement.
- If there is a surplus, pressing TRIM will reduce the amount on the input to requirements, leaving all other inputs alone.
=> Inputs: Multiple inputs TRIM / SATISFY button logic fixes

web/src/assets/styles/global.scss, web/src/components/Templates.vue, web/src/components/planner/PlannerFactoryImports.vue, web/src/components/planner/PlannerFactorySatisfactionItems.vue, web/src/components/planner/StatisticsItems.vue, web/src/components/planner/StatisticsResources.vue, web/src/components/planner/products/Product.vue, web/src/utils/factory-management/dependencies.spec.ts, web/src/utils/factory-management/inputs.ts, web/src/utils/factory-management/products.ts, web/src/utils/factory-management/satisfaction.spec.ts, web/src/utils/factory-management/satisfaction.ts, web/src/utils/factory-setups/220-byproduct-only-part.ts, web/src/utils/factory-setups/338-satisfaction-chips.ts
Closes #220 
Closes #338 
Closes #339 
- Refactor Satisfaction item button code, simplifying the conditions and fully tested.
- Added "Correct Manually" "button" with tooltip. #220 
- Added "Fix import" multiple handling. #339 
- #338 
- Added various chips to denote the role of the part within the factory. These roles are:
- Product
- Byproduct
- Imported
- Raw
- Internal
- A part can at maximum be a Product, Byproduct, Imported and Internal.
- Made Raw Items distinct in colour (cyan) sitewide.
- Added "Raw" chip to the entry next to the Satisfaction surplus / deficit, informing the user that this a automatically assumed part.
=> Satisfaction section enhancements, handle Fix Product bug for Byproducts, refactor button code

web/src/components/Templates.vue, web/src/components/planner/PlannerFactory.vue
fix(web): Show deficits and surpluses better in hidden view.
Closes #350
=> Improve surplus and deficits representations in hidden / collapsed view

web/src/components/Templates.vue, web/src/components/planner/PlannerFactorySatisfactionItems.vue, web/src/stores/game-data-store.spec.ts, web/src/stores/game-data-store.ts, web/src/utils/factory-management/power.spec.ts, web/src/utils/factory-management/power.ts, web/src/utils/factory-management/satisfaction.spec.ts, web/src/utils/factory-management/satisfaction.ts, web/src/utils/factory-setups/267-nuclear-waste-handling.ts, web/src/utils/factory-setups/269-power-generator-multiple-same.spec.ts, web/src/utils/factory-setups/269-power-generator-multiple-same.ts, web/src/utils/numberFormatter.ts
Closes #267 
1. Open preview site. https://satisfactory-factories-h0iyknrc0-maelstromeous-projects.vercel.app/
2. Open templates.
3. Choose `#267: Nuclear Waste Handling` (bottom button).
1. Add Uranium via +Generator button.
2. Check Uranium waste is satisfied, it should amount to 0.5 UFRs and create 25 NW as a byproduct, and 6.25GW.
4. Add Plutonium  via +Generator button.
5. Check Plutonium waste is satisfied, it should amount to 1 PFR and create 10 PW as a byproduct and 25GW.
1. Using the previously added generators, decrease one of the fuel rods.
2. The associated fuel should now be unsatisfied and show "Fix Generator".
3. Pressing Fix Generator should rectify the generator group.
Increasing the demand for the waste should also make the fix generator button appear.
1. Add Nuclear …
=> Satisfaction: Nuclear / Plutonium Waste handling

web/src/components/Templates.vue, web/src/components/Toast.vue, web/src/components/planner/products/Product.vue, web/src/utils/eventBus.ts, web/src/utils/factory-management/common.ts, web/src/utils/factory-management/parts.spec.ts, web/src/utils/factory-management/parts.ts, web/src/utils/factory-management/products.spec.ts, web/src/utils/factory-management/products.ts, web/src/utils/factory-setups/375-byproduct-ghost-surplus.ts, web/src/utils/helpers.ts
Closes #375 
Closes #385 
When the user selects a byproduct as a product (e.g. Heavy Oil Residue using the Rubber recipe) the planner would double count the byproduct, and the original producing product (Rubber) would not be counted at all.
This change now enforces the use of the actual product recipe as the product selection, and informs the user that such a change has been made.
=> Better byproduct product selection handling & waste product removal fix
