satisfactory-factories/application

- web/src/components/planner/Introduction.vue
- web/src/components/planner/Planner.vue
> fix(web): Closes #44 - event name was incorrect and the code wasn't being executed correctly.

- web/src/components/Auth.vue
- web/src/components/Navigation.vue
- web/src/layouts/default.vue
> 42 header resize

- web/src/utils/factory-management/mocks/mockRecipes.ts
- web/src/utils/factory-management/products.spec.ts
- web/src/utils/factory-management/products.ts
> fix(web): #9 Enabled user to be able to select multiple products by the same type with different recipes.

- README.md
This pull request includes a small but important change to the `README.md` file. The change adds a hyperlink to the web tool mentioned in the documentation.
> Update README.md to include link to the tool!

- web/src/components/planner/PlannerFactoryProducts.vue
> Add debug buttons to factory cards

- .github/workflows/issue-milestone.yml
Add a new GitHub Actions workflow to manage issue milestones based on labels and issue state.
* **New Workflow File**: Add `.github/workflows/issue-milestone.yml` to handle issue labeling and milestone management.
* **Trigger Events**: Listen for `issues` events with `labeled` and `closed` actions.
* **Add Milestone**: Add "High Priority" milestone to issues labeled with "P1".
* **Remove Milestone**: Remove "High Priority" milestone from closed issues with the "P1" label.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/satisfactory-factories/application/pull/85?shareId=d6a44d1c-7535-4d00-bd88-8aa5b3aeb011).
> Add GitHub Actions workflow for issue milestone management

- web/src/components/planner/PlannerFactoryProducts.vue
- web/src/components/planner/PlannerFactorySatisfaction.vue
- web/src/stores/game-data-store.ts
- web/src/utils/factory-management/products.spec.ts
- web/src/utils/factory-management/products.ts
Closes #76 
These changes might be a bit controversial as I added functions to the `game-data-store.ts`.  
If you have other suggestions, let me know!
> fix(web): #76 fix +product button in Satisfaction

- web/src/utils/factory-management/products.ts
> fix(web): fix rounding errors in product calculation

- web/src/components/planner/Planner.vue
- web/src/components/planner/PlannerFactory.vue
Closes #142 
I was going to add a test, but the function is currently in a .vue file and I think it is fine there. However currently we cannot test vue files without reconfiguring jest and adding packages.
Should we tackle that? Also I would recommend using vitest, as it uses the same api and has better vue support
> Fix linked cloned factories

- web/src/stores/game-data-store.ts
- web/src/utils/factory-management/buildings.ts
- web/src/utils/factory-management/exports.spec.ts
- web/src/utils/factory-management/exports.ts
Closes #134 
The error occurred when an item gets removed from the input
The Buildings & Power section also got broken when that happened, I fixed that too
> Fix broken exports section

- .github/workflows/issue-management.yml
- web/src/components/planner/Planner.vue
- web/src/components/planner/PlannerFactory.vue
- web/src/components/planner/PlannerFactoryExports.vue
- web/src/components/planner/PlannerFactoryProducts.vue
- web/src/components/planner/PlannerFactorySatisfaction.vue
- Added new 'Fix Production' button to the Product (tried to size it the best I could to match)
- Moved logic for fixing the part to 'Factory' vue level
- Updated both of the buttons to 'green' (as requested by Maelstrom)
Closes #27
> feat(web): Added new FixProduction button to Products (and made them green)

- .github/codeql/config.yml
We may need to create other configuration files - let's see if this is enough. 
<HR>
This pull request includes changes to the `.github/codeql/config.yml` file to improve the CodeQL configuration by ignoring false positives related to mock tokens used for testing purposes.
> Added codeql config file

- .github/workflows/issue-management.yml
Tested this in another repo, hopefully this one is magic and works. 🪄 
fixes #131
> Update to Action to remove needs triage automagically in some scenarios.

- backend/backend.ts
> fix(backend): Increased size of payload bodies

- web/src/components/Auth.vue
- web/src/components/FactoryDebug.vue
- web/src/components/Navigation.vue
- web/src/components/TabNavigation.vue
- web/src/components/ko-fi.vue
- web/src/components/planner/Notice.vue
- web/src/components/planner/Planner.vue
- web/src/components/planner/PlannerFactory.vue
- web/src/components/planner/PlannerFactoryImports.vue
- web/src/components/planner/PlannerFactoryProducts.vue
- web/src/components/planner/PlannerFactorySatisfaction.vue
- web/src/components/planner/PlannerStatistics.vue
- web/src/layouts/default.vue
Work towards #82 
Not perfect yet but usable
You need to reload the page after switching to mobile if you started off in desktop mode, otherwise the left tray will be broken
> Mobile optimisation

- web/src/components/planner/PlannerFactoryImports.vue
> fix(web): Fixes import button

- web/src/components/planner/Notice.vue
> fix(web): Fixed logic on how the bugs tray option is detected, dunno how this wasn't a bug before!

- web/src/components/planner/Planner.vue
> fix(web): Made teleport respect the same rendering condition as it's target, otherwise it breaks the site.

- web/src/components/ShareButton.vue
> Fix sharing

- web/src/components/planner/PlannerStatistics.vue
> Update PlannerStatistics.vue to setleaves, Mycelia, and wood to infinity

- backend/backend.ts
- backend/interfaces/FactoryInterface.ts
- web/src/components.d.ts
- web/src/components/planner/PlannerFactory.vue
- web/src/components/planner/PlannerFactoryNotes.vue
- web/src/components/planner/PlannerFactorySatisfaction.vue
- web/src/components/planner/PlannerFactoryTodos.vue
- web/src/interfaces/planner/FactoryInterface.ts
- web/src/stores/app-store.ts
- web/src/utils/factory-management/factory.ts
Closes #250 
Adds ability to add tasks and notes to each factory.
Demo: https://discord.com/channels/1308761343611899904/1308763451253985330/1313271202021773402
> Add factory Notes and Todo list

- web/src/components/planner/Planner.vue
- web/src/components/planner/PlannerFactoryImports.vue
- web/src/stores/sync-store.ts
> Factory Import candidate tweaks

- parsing/gameData.json
- web/public/gameData_v1.0-25.json
- web/src/config/config.ts
(see [patch notes](https://store.steampowered.com/news/app/526870/view/512943879502168877) for details.
> Refreshing game data after recent Ficmas game balancing changes.

- .github/workflows/issue-management.yml
[for example](https://github.com/satisfactory-factories/application/actions/runs/12267342963).
> fix: extra checks to ensure the remove label doesn't fail if the label is non-existent

- parsing/gameData.json
- parsing/src/interfaces/ParserPart.ts
- parsing/src/parts.ts
- web/public/gameData_v1.0-27.json
- web/src/config/config.ts
- web/src/interfaces/DataInterface.ts
The first in a series of parser upgrades.
Collectables are not used, there are no issues to address them, not correct, and based on Discord conversation, can be removed to simply logic
> fix: removed unused collectables data from game data files

- web/src/interfaces/planner/FactoryInterface.ts
- web/src/stores/app-store.spec.ts
- web/src/stores/app-store.ts
- web/src/utils/factory-management/factory.ts
> fix(web): Fixed factory data migrations and added tests to ensure it is fixed. Added data version.

- web/src/components/Templates.vue
- web/src/utils/factory-management/inputs.spec.ts
- web/src/utils/factory-setups/321-inputs-byproducts.ts
Closes #321 
Related #299 
Was fixed in #325
> Added test cases to ensure inputs properly handle byproducts

- web/src/utils/factory-management/inputs.spec.ts
- web/src/utils/factory-management/inputs.ts
> fix(web): Fixes #328, otherImports was not checking it was the same part

- web/src/components/Templates.vue
- web/src/utils/factory-management/inputs.spec.ts
- web/src/utils/factory-management/products.spec.ts
- web/src/utils/factory-management/products.ts
- web/src/utils/factory-setups/242-inputs-byproducts.ts
- web/src/utils/factory-setups/321-product-byproduct-trimming.spec.ts
- web/src/utils/factory-setups/321-product-byproduct-trimming.ts
Closes #321 
Closes #264 
Closes #271 
Related #299
> Product / Byproducts trim fixes

- web/src/components/Templates.vue
- web/src/utils/factory-setups/242-inputs-byproducts.ts
- web/src/utils/factory-setups/251-multiple-imports.spec.ts
- web/src/utils/factory-setups/251-multiple-imports.ts
> feat(web): Created scenario plan for #251

- web/src/components/Templates.vue
- web/src/components/planner/products/Product.vue
- web/src/stores/app-store.ts
- web/src/utils/factory-management/products.spec.ts
- web/src/utils/factory-management/products.ts
- web/src/utils/factory-management/validation.spec.ts
- web/src/utils/factory-management/validation.ts
- web/src/utils/factory-setups/341-fissible-uranium-issues.spec.ts
- web/src/utils/factory-setups/341-fissible-uranium-issues.ts
Closes #341 
Migration of all handling code for the fields located here:
While I appreciate the previous work of @immerrr, I had to re-write some of it in terms of the function argument overrides, as they were incredibly hard to test and I wasn't understanding it at all, was too "magic". Sorry.
**This is fully backed by tests**.
> Products: Refactor of byproduct / ingredient fields

- web/src/components/planner/Planner.vue
- web/src/components/planner/PlannerFactorySatisfactionBuildings.vue
- web/src/components/planner/StatisticsBuildings.vue
- web/src/components/planner/StatisticsFactorySummary.vue
- web/src/components/planner/products/Product.vue
- web/src/utils/factory-management/common.ts
> refactor(web): Move getBuildingDisplayName out of planner

- web/src/components/TabNavigation.vue
- web/src/stores/app-store.ts
> feat(web): Moved confirmation prompt for deleting tabs to the component

- web/src/components/planner/PlannerTooManyFactoriesOpen.vue
> feat(web): Added ability to dismiss the too many factories warning until refresh.

- web/src/stores/app-store.ts
> Refactor loading sequence

- web/src/components/Loading.vue
- web/src/components/TabNavigation.vue
- web/src/components/Templates.vue
- web/src/components/planner/Introduction.vue
- web/src/components/planner/Planner.vue
- web/src/components/planner/PlannerGlobalActions.vue
- web/src/stores/app-store.spec.ts
- web/src/stores/app-store.ts
- web/src/utils/eventBus.ts
- web/src/utils/factory-management/factory.spec.ts
- web/src/utils/factory-management/factory.ts
Taking the successes from failed PR #346 and applying them.
> App Store tests, loading tweaks, other general enhancements

- web/src/components/planner/PlannerFactory.vue
- web/src/interfaces/planner/FactoryInterface.ts
- web/src/stores/app-store.ts
- web/src/utils/factory-management/factory.ts
- web/src/utils/factory-management/syncState.spec.ts
- web/src/utils/factory-management/syncState.ts
- web/src/utils/factory-setups/maels-big-boi-plan.ts
Closes #270 
feat(web): Refactored and enhanced factory gamesync, now adding power generators and fully backed by tests.
feat(web): Removed management of sync state out of PlannerFactory into utility dedicated for it.
> GameSync enhancements

- web/src/components/planner/products/Product.spec.ts
- web/src/components/planner/products/Product.vue
- web/src/interfaces/planner/FactoryInterface.ts
- web/src/utils/factory-management/buildings.ts
- web/src/utils/factory-setups/269-power-generator-multiple-same.spec.ts
- web/src/utils/factory-setups/269-power-generator-multiple-same.ts
> Correctly calculate multiple groups of power producers

- web/src/components/planner/PlannerFactoryImports.vue
> Updated input quantity field to number input to prevent breaks

- web/src/components/planner/PlannerFactoryImports.vue
- web/src/utils/factory-management/dependencies.spec.ts
- web/src/utils/factory-management/dependencies.ts
- web/src/utils/factory-management/factory.ts
- web/src/utils/factory-management/inputs.spec.ts
- web/src/utils/factory-management/inputs.ts
- web/src/utils/factory-setups/simple-plan.spec.ts
Closes #373 
Related #378 
Abstracted the delete input code into a testable utility, applied tests to it. Now properly deletes inputs and has both factories updated.
> Refactored how inputs are deleted, now backed by tests

- web/src/components/planner/PlannerFactoryImports.vue
- web/src/components/planner/products/Product.spec.ts
- web/src/utils/factory-management/inputs.spec.ts
- web/src/utils/factory-management/inputs.ts
- web/src/utils/factory-management/products.spec.ts
- web/src/utils/factory-management/products.ts
Closes #374 
Prevent naughty things going into input quantities
> Inputs Validation

- web/src/components/planner/PlannerFactory.vue
> feat(web): Added better check for if a factory can be game synced

- web/src/components/planner/PlannerFactorySatisfactionBuildings.vue
- web/src/components/planner/products/PowerProducer.vue
- web/src/components/planner/products/Product.vue
> Fixed building icons not updating when changed in place

- README.md
- parsing/gameData.json
- web/public/gameData_v1.0-29.json
- web/src/config/config.ts
Updated files to include changes as of 10-Jun/ v1.1, (mostly just naming changes, nothing major).
> New 1.1 data file, fully parsed (take 2)
